baseURL = 'https://geeneglungo.github.io/'
languageCode = 'en-us'
title = 'Geene Glungo'
theme = "smol"

enableRobotsTXT = true

# Parameters
[params]
    subtitle = "Hello!"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/"
        weight = 1 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://mastodon.social/@geeneglungo"
        weight = 2 

    [[menu.footer]]
        name = "YouTube"
        url = "https://youtube.com/@geeneglungo"
        weight = 3 

    [[menu.footer]]
        name = "RSS"
        url = "/index.xml"
        weight = 4

[outputs]
  home = ["HTML", "RSS"]

[Author]
    name = "Geene Glungo"
    email = "geeneglungo@proton.me"

